[tool.black]
line-length = 120
target-version = ['py314']
force-exclude = '''test'''

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.coverage.run]
omit = ["tests/*"]

[tool.mypy]
check_untyped_defs = true
exclude = "tests"
